### PR TITLE
Feat: Case converter tool

### PR DESCRIPTION
**Pull request by vinayharwani13**
## Type of Pull Request

- [ ] Bug fix
- [x] Enhancement

Related Issue #s or links (if any): #50 

## Description of Changes

This PR adds a case converter tool. Here is the screenshot.

Screenshot 2022-10-16 at 12 56 10 AM

### CODE REVIEW

**Review by dlford — CHANGES_REQUESTED** [review]
@vinayharwani13 great job on this! Sorry it took so long to review!

Everything looks good here except mobile, can we make it fit the screen width?

**Review by dlford — CHANGES_REQUESTED** [review]
@vinayharwani13 great job on this!

I made some changes for you since i18n was added after you started on this, so please pull down the changes and `npm install` before you continue.

Two minor fixes if you don't mind:

1. Lets make "Case Options" persist across page loads (use `useLocalState`)
2. Lets make the output update when the input changes too, currently it only changes when you select a case option, but it should work with both events.

**Comment by vinayharwani13** [comment]
Hi @dlford , Sorry it took me this long. 
I have made the changes. Let me know if anything else needs improvement.
Thanks.

**Review by dlford — APPROVED** [review]
Awesome, looks great, thanks so much!

**Pull request merged**
