### PR TITLE
HTML Format

### PR DESCRIPTION
**Pull request by mvarrieur**
## Type of Pull Request

- [ ] Bug fix
- [x] Enhancement

Related Issue #s or links (if any): #8 

## Description of Changes
* Add HTML Formatter via Prettier

_Note_: I tried finding a minifier that would work in the browser but didn't have luck, the few I tried required node

### CODE REVIEW

**Comment by dlford** [comment]
@mvarrieur Looks like there is a TypeScript compiler error:

ksnip_20221003-190218

**Comment by mvarrieur** [comment]
@dlford Thanks, fixed that and resolved merge conflicts.

**Review by dlford — CHANGES_REQUESTED** [review]
@mvarrieur great job on this! Can we add an error message like the JSON tool so it's clear what is wrong with the input when there is an error?

**Comment by mvarrieur** [comment]
> I can take a look at what prettier prov

> @mvarrieur great job on this! Can we add an error message like the JSON tool so it's clear what is wrong with the input when there is an error?

I can take a look at what prettier provides in the error that gets thrown later tonight or tomorrow, but I'm not quite sure what level of detail is there

**Comment by dlford** [comment]
> > I can take a look at what prettier prov
> 
> > @mvarrieur great job on this! Can we add an error message like the JSON tool so it's clear what is wrong with the input when there is an error?
> 
> I can take a look at what prettier provides in the error that gets thrown later tonight or tomorrow, but I'm not quite sure what level of detail is there

Thank you! It doesn't have to be super specific, as long as it gives some idea as to what the problem is.

**Comment by mvarrieur** [comment]
@dlford Added error output from prettier to the page
Screenshot 2022-10-04 at 17-47-24 DeveloperTools Tech

**Comment by mvarrieur** [comment]
Sorry not sure why I'm not seeing the TS errors on my side until I push, taking a look now.

**Comment by dlford** [comment]
@mvarrieur Perfect, I like that you put the error message above the output field, I might do that for JSON to. Thank you!

**Pull request merged**
