### PR TITLE
added the markup and part-logic for the number base converter

### PR DESCRIPTION
**Pull request by tobySolutions**
## Type of Pull Request

- [ ] Enhancement

Related Issue #s or links (if any): 

## Description of Changes
I was able to build the markup for the number base converter and I added a bit of logic to the conversion. Sadly I couldn't't do more than that. I hope this gets merged and someone else continues from there.

### CODE REVIEW

**Comment by dlford** [comment]
@tobySolutions This can't be merged as is, I'm sorry for that, but this code is failing all tests. Is there anything I can do to help you with this?

**Comment by tobySolutions** [comment]
Oh! I forgot to actually write tests for the feature I added.

Regardless, I didn't actually complete the feature, I just gave it a cool
markup.

**Comment by dlford** [comment]
@tobySolutions @nobalpha is going to take this over and use your existing work if able to, thanks for the part you played in it!

**Comment by tobySolutions** [comment]
My pleasure!!

**Pull request closed without merging**
