### PR TITLE
feat: add regex testing tool

### PR DESCRIPTION
**Pull request by gaston-flores**
## Type of Pull Request

- [ ] Bug fix
- [x] Enhancement

Related Issue #s or links (if any): #9

## Description of Changes

This PR adds a Regex testing tool:

image

### CODE REVIEW

**Comment by gaston-flores** [comment]
Also just FYI @dlford I think you are [missing a `key` here](https://github.com/developertools-tech/developertools.tech/blob/6a61976ff836c1536ff01ba1591b4934dcf737c5/components/Layout.tsx#L303), I'm getting this warning on my console:
```
Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at a
    at Layout (webpack-internal:///./components/Layout.tsx:124:19)
    at IndexPage
    at InnerThemeProvider (/workspaces/developertools.tech/node_modules/@mui/system/ThemeProvider/ThemeProvider.js:29:39)
    at ThemeProvider (/workspaces/developertools.tech/node_modules/@mui/private-theming/node/ThemeProvider/ThemeProvider.js:55:5)
    at ThemeProvider (/workspaces/developertools.tech/node_modules/@mui/system/ThemeProvider/ThemeProvider.js:49:5)
    at MyApp (webpack-internal:///./pages/_app.tsx:39:13)
    at StyleRegistry (/workspaces/developertools.tech/node_modules/next/dist/styled-jsx/dist/index/index.js:671:34)
    at AppContainer (/workspaces/developertools.tech/node_modules/next/dist/server/render.js:280:29)
    at AppContainerWithIsomorphicFiberStructure (/workspaces/developertools.tech/node_modules/next/dist/server/render.js:309:57)
    at div
    at Body (/workspaces/developertools.tech/node_modules/next/dist/server/render.js:596:21)
```

**Comment by dlford** [comment]
> Also just FYI @dlford I think you are [missing a `key` here](https://github.com/developertools-tech/developertools.tech/blob/6a61976ff836c1536ff01ba1591b4934dcf737c5/components/Layout.tsx#L303), I'm getting this warning on my console:
> 
> ```
> Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
>     at a
>     at Layout (webpack-internal:///./components/Layout.tsx:124:19)
>     at IndexPage
>     at InnerThemeProvider (/workspaces/developertools.tech/node_modules/@mui/system/ThemeProvider/ThemeProvider.js:29:39)
>     at ThemeProvider (/workspaces/developertools.tech/node_modules/@mui/private-theming/node/ThemeProvider/ThemeProvider.js:55:5)
>     at ThemeProvider (/workspaces/developertools.tech/node_modules/@mui/system/ThemeProvider/ThemeProvider.js:49:5)
>     at MyApp (webpack-internal:///./pages/_app.tsx:39:13)
>     at StyleRegistry (/workspaces/developertools.tech/node_modules/next/dist/styled-jsx/dist/index/index.js:671:34)
>     at AppContainer (/workspaces/developertools.tech/node_modules/next/dist/server/render.js:280:29)
>     at AppContainerWithIsomorphicFiberStructure (/workspaces/developertools.tech/node_modules/next/dist/server/render.js:309:57)
>     at div
>     at Body (/workspaces/developertools.tech/node_modules/next/dist/server/render.js:596:21)
> ```

Yes I saw that too, not sure how it got in there but I'll track it down, thanks!

**Review by dlford — CHANGES_REQUESTED** [review]
@gaston-flores stellar work here! I really like the UI that you came up with.

I think my vision of this tool may not have been documented well enough in the issue, that's on me, but here are some things I'd like to see changed, if you feel they are out of scope of the original issue please feel free to skip them and I'll make a new issue for that work.

1. allow the leading and tailing `/` for adding flags (e.g. `g`)
2. allow for replace syntax (e.g. `/regex/replacewith/`) and show replaced output

Barring that, I think the Regex input could match the width of the test case box visually, then all we need is tests.

**Comment by gaston-flores** [comment]
Ooooh, gotcha! If you don't mind I think those would be best for a separate PR. I could take a crack at adding the flags, but my solution for showing the match/capture groups would need some refactoring to work with the `g` flag.

**Comment by dlford** [comment]
@gaston-flores I don't mind, no need to do a heavy refactor if you don't want to.

**Comment by dlford** [comment]
@gaston-flores it's better to hash the content of a node than use the array index, an example can be found here - https://github.com/developertools-tech/developertools.tech/blob/main/pages/lorem-ipsum.tsx#L231

**Comment by dlford** [comment]
Also, thanks for adding the global flag, looks great!

**Comment by gaston-flores** [comment]
Oh, gotcha! I'll give it a try! I don't know why, but the eslint errors are not showing up in my local console. Thanks!

**Comment by dlford** [comment]
I recently changed the eslint config because it was missing a line for the airbnb rules, maybe your local copy doesn't have that change yet?

The hashing bit helps keep each node unique in an array, in some cases using the array index can cause weird behavior (e.g. replacing the content of a node may not render correctly because the key didn't change).

**Comment by gaston-flores** [comment]
Yep, works now that I rebased the branch!

I'm kinda running into strange issues when using `hash` though:

https://user-images.githubusercontent.com/18354222/194915400-3aeb9730-89bf-40e8-bc34-7577128b4c6a.mov

It seems tying the array key to `testCase` creates a new input on every keypress, losing focus in the process. Here's the code. Here's what I'm doing:

```tsx
{testCases.map((testCase, index) => {
  const id = hash(testCase);
  return (
    <RegexTestCase
      key={id}
      index={index}
      testCase={testCase}
      regex={regex}
      onDelete={handleRemoveTestCase}
      onInput={handleTestCaseInput}
      deleteDisabled={testCases.length === 1}
    />
  );
})}
```
I'll leave it with `disable` for now.

**Comment by dlford** [comment]
@gaston-flores Oh yeah, that's not good. Go ahead and disable the eslint rule at the top of the file then and use the array index, please add a note on the next line `// TODO: Find a better way to replace array index keys`, or something of that nature. I know in the past I've created an ID dynamically and assigned it to each node, not sure how I did it off the top of my head.

In any case, if the array index is working, I'm fine with it for now.

Thanks!

**Review by dlford — APPROVED** [review]
Fantastic, thanks @gaston-flores!

**Pull request merged**
