### PR TITLE
[i18n] Spanish translation

### PR DESCRIPTION
**Pull request by Lio-n**
## Type of Pull Request

- [x] Bug fix
- [x] Enhancement

Related Issue #s or links (if any): [#67](https://github.com/developertools-tech/developertools.tech/issues/67)

## Description of Changes
Spanish Translation for **caseConverter.json** and **characterCounter.json**.

### CODE REVIEW

**Review by dlford — CHANGES_REQUESTED** [review]
Looks like there are still some Spanish translations missing - https://github.com/developertools-tech/developertools.tech/issues/67

**Comment by Lio-n** [comment]
Hi, what translations are missing exactly?
Do you mean what's in the **caseConverter.json** file?

I updated "titleCase", "lowerCase", "upperCase" and "sarcasmCase". The others are not, because they are mostly used in English and in Spanish the translation is not consistent.

**Comment by dlford** [comment]
> Hi, what translations are missing exactly? Do you mean what's in the **caseConverter.json** file?
> 
> I updated "titleCase", "lowerCase", "upperCase" and "sarcasmCase". The others are not, because they are mostly used in English and in Spanish the translation is not consistent.

@Lio-n Please see the list in #67, all the missing translations are listed there

**Comment by Lio-n** [comment]
Thanks, I got a little lost. 
Complete all this:
- [x] base64.ascii
- [x] colors.cssFilterGenerator
- [x] colors.cssFilterGeneratorDescription
- [x] colors.loss
- [x] colors.regenerate
- [x] colors.selectedColor
- [x] colors.transformedColor
- [x] common.caseConverter
- [x] common.charCounter
- [x] css.title
- [x] css.css
- [x] html.title
- [x] html.html
- [x] htmlCharCodes.title
- [x] imageConverter.title
- [x] imageConverter.png
- [x] imageConverter.jpg
- [x] imageConverter.webp
- [x] jsonFormat.title
- [x] loremIpsum.title
- [x] loremIpsum.willFerrell
- [x] loremIpsum.jeffGoldblum
- [x] regex.title
- [x] regex.testCasePlaceholder
- [x] regex.deleteTestCase
- [x] textDiff.title
- [x] textDiff.jsonInvalid
- [x] top.recentChanges
- [x] urlEncode.title
- [x] uuid.title
- [x] uuid.url
- [x] uuid.dns
- [x] characterCounter.title
- [x] characterCounter.description
- [x] characterCounter.inputText
- [x] characterCounter.characters
- [x] characterCounter.words
- [x] characterCounter.sentences
- [x] characterCounter.paragraphs

also add this:
- [x] caseConverter.description
- [x] caseConverter.inputText
- [x] caseConverter.caseOptions
- [x] caseConverter.outputText
- [x] caseConverter.output
- [x] caseConverter.kebabCase
- [x] caseConverter.camelCase
- [x] caseConverter.pascalCase
- [x] caseConverter.snakeCase
- [x] caseConverter.screamingSnakeCase
- [x] caseConverter.screamingKebabCase
- [x] caseConverter.titleCase
- [x] caseConverter.lowerCase
- [x] caseConverter.upperCase
- [x] caseConverter.sarcasmCase

**Pull request merged**
