### PR TITLE
Feature: Color contrast checker

### LINKED ISSUE #96: [Req]: Add Text Contrast Tool
### Contact Details

_No response_

### Explain the proposed feature

Add a text contrast tool to the color tool page for testing accessibility of text colors over background colors. Something similar to this tool - https://webaim.org/resources/contrastchecker/

### Explain the possible use cases for the feature

_No response_

### Any other details you would like to provide?

_No response_

### PR DESCRIPTION
**Pull request by sushma1031**
## Type of Pull Request

- [x] Enhancement

Related Issue #s or links (if any): 
Fixes #96

## Description of Changes
Added a text contrast checking tool in the `colors` page, similar to the website referenced in the issue. Added the required namespace and tests as well.

### CODE REVIEW

**Review by dlford — CHANGES_REQUESTED** [review]
@sushma1031 great job on this!

Just a couple of adjustments needed:

- [ ] "Normal Text", "Large Text", and "Graphical Objects and User Interface Components" headings should be `h3`s, not `h5`s
- [ ] The foreground and background translations strings shouldn't be in all caps
- [ ] The "contrast ratio" label is not translated, also needs to be title cased
- [ ] Can the "swap" button fit in the copy/paste button group to the left of "copy"?
- [ ] The text input field under "Graphical Objects and User Interface Components" doesn't match the selected colors, is this intentional?
- [ ] The value of the contrast ratio should not be an `h3` as it is not a heading

**Comment by sushma1031** [comment]
- [ ]  I think the swap button can fit on the left, which text field should I add it to?
- [ ] The text input field's border matches the selected foreground colour, same as the referenced website.
- [ ] Can we still have the contrast ratio value in a larger size, as in, change it to a `p` element and increase the font size?

I'll take care of the remaining changes.

**Comment by dlford** [comment]
@sushma1031 I'm not sure what you mean by "I think the swap button can fit on the left, which text field should I add it to?"? I mainly just wanted the swap button to not be below the other buttons for that field, does that make sense? Apologies for not being more clear.

The input text makes sense, that can stay as is.

Yes, the contrast text can be larger, the current size is perfectly fine, just the semantics of heading tags does not make sense for that.

Thank you!

**Comment by sushma1031** [comment]
> I'm not sure what you mean by "I think the swap button can fit on the left, which text field should I add it to?"? I mainly just wanted the swap button to not be below the other buttons for that field, does that make sense? Apologies for not being more clear.

Oh, right, I understood what you mean. The swap button isn't actually part of the text field, its purpose is to allow the user to swap the background and foreground colors, so I thought placing it in between the fields would be appropriate. 
Similar to this:
IMG-20231028-WA0000

**Comment by dlford** [comment]
@sushma1031 I see what you mean, maybe it just needs a little more vertical margin to get it away from the other buttons on that field? Whichever you think is best.

**Comment by sushma1031** [comment]
Yes, I agree that a little more vertical margin would b better, I'll add the same.

**Comment by sushma1031** [comment]
>  "Normal Text", "Large Text", and "Graphical Objects and User Interface Components" headings should be `h3`s, not `h5`s

image

@dlford I made the mentioned headings h3, and I think they look too large. Can we reduce the font size?

**Comment by sushma1031** [comment]
> maybe it just needs a little more vertical margin to get it away from the other buttons on that field? Whichever you think is best.

image

Is this much vertical margin sufficient?

**Comment by sushma1031** [comment]
@dlford I made the requested changes, let me know if there's anything else!

**Comment by dlford** [comment]
@sushma1031 looks great, thank you!

**Pull request merged**
