### PR TITLE
added text-diff tool

### PR DESCRIPTION
**Pull request by AnkitaMalik22**
## Type of Pull Request

- [ ] Bug fix
- [x] Enhancement

Related Issue #s or links (if any):

### CODE REVIEW

**Comment by dlford** [comment]
@AnkitaMalik22 Please check the deploy log for errors, I think you just need to run `npm run lint` to auto-fix some linting errors.

https://app.netlify.com/sites/developertools-tech/deploys/633e840b3a748b00080bc41b

**Review by dlford — CHANGES_REQUESTED** [review]
@AnkitaMalik22 great job on this! We need to address a few things before we can merge.

Also, the test file is empty, I am happy to help with that if needed?

One last thing, the two input fields should wrap on mobile, they get too narrow to be very usable when they are side by side.

**Comment by AnkitaMalik22** [comment]
> @AnkitaMalik22 great job on this! We need to address a few things before we can merge.
> 
> The two text fields seem to change when the page is reloaded, the keys on `useLocalState` need to be different so they are saved separately.
> 
> Also, the test file is empty, I am happy to help with that if needed?
> 
> One last thing, the two input fields should wrap on mobile, they get too narrow to be very usable when they are side by side.

I'm sorry I've never worked on test files before.

**Comment by dlford** [comment]
@AnkitaMalik22 I will take some time to figure out whats going on here and give you some advice, ok?

**Comment by dlford** [comment]
@AnkitaMalik22 I've rebased your branch onto the dev branch here - https://github.com/developertools-tech/developertools.tech/tree/text-diff-rebase

You can force push it to your fork like this:

```sh
git remote add devtoolstech https://github.com/developertools-tech/developertools.tech
git fetch devtoolstech
git checkout text-diff-rebase
git branch -D text-diff
git checkout -b text-diff
git push -f -u origin text-diff
```

That should hopefully get all the tests passing so I can do a review.

Let me know if you have any questions :-)

**Pull request merged**
