### PR TITLE
feat: YAML

### PR DESCRIPTION
**Pull request by fandykun**
## Type of Pull Request

- [ ] Bug fix
- [x] Enhancement

Related Issue #s or links (if any): #4

WIP:
- [ ] Unit Test

## Description of Changes
Add YAML Page

### CODE REVIEW

**Comment by fandykun** [comment]
Hi @dlford , I've been stuck on unit test while I using package `yaml` and gonna testing it.
```
<dir>/node_modules/yaml/browser/index.js:3
import * as YAML from './dist/index.js'
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

can u help me with this issue?

**Comment by dlford** [comment]
@fandykun of course, I'll take a look and get back to you in the next few days.

**Comment by dlford** [comment]
@fandykun I think you just need to do `import YAML from '../pages/yaml';`, take a look at some of the other tests for reference. If you need anything else please feel free to reach out!

**Comment by dlford** [comment]
@fandykun are you still having a hard time with this? Happy to help out if you are?

**Comment by fandykun** [comment]
@dlford Hi, sorry for late response..

Yeah, its still unsolved yet, probably need some changes config on jest. Or I will change its package if still not working on unit test.

**Comment by dlford** [comment]
@fandykun I think you don't need to use the `dist` directory, you can import from the relative path of the project root.

**Pull request closed without merging**
