### PR TITLE
Add TOTP

### LINKED ISSUE #97: [Req]: TOTP Debugger
### Contact Details

_No response_

### Explain the proposed feature

A new tool that can generate TOTP secret keys and the OTP codes for them, or accept a user secret.

### Explain the possible use cases for the feature

When developing applications that utilized TOTP, it would be nice to have a web tool instead of enrolling a bunch of temporary secrets for testing

### Any other details you would like to provide?

_No response_

### PR DESCRIPTION
**Pull request by mvarrieur**
## Type of Pull Request

- [ ] Bug fix
- [x] Enhancement

Related Issue #s or links (if any): 

Fixes #97 

## Description of Changes

@dlford I think I have most of the functionality for TOTP here. Just wanted to put up a draft PR so you could give me any feedback before I start writing tests.

### CODE REVIEW

**Comment by dlford** [comment]
@mvarrieur the code looks pretty clean, but I can't review the UI yet because there are some type errors happening, can you take a look?

**Comment by mvarrieur** [comment]
> @mvarrieur the code looks pretty clean, but I can't review the UI yet because there are some type errors happening, can you take a look?

Types/Formatting errors are fixed if you want to check out the UI. I'll start adding tests later tonight or this weekend when I get a few minutes.

**Review by dlford — CHANGES_REQUESTED** [review]
Thanks @mvarrieur!

The UI looks great, there are a few small issues with the functionality:

- Typing into the SECRET field only updates the URI field every other character, or somewhat
- Pasting to the SECRET field using the paste button doesn't do anything
- Changing the SECRET field does not change the Current Token field even when the URI and QR code change

Some minor improvements that are not required for acceptance of this PR, but would be nice to have:

- A countdown timer for the Token field
- Fixed width QR code, it's a bit large around 1190px
- A random SECRET instead of a static one if there isn't anything currently in local storage

**Comment by mvarrieur** [comment]
>     * ✅ Pasting to the SECRET field using the paste button doesn't do anything 
>     * ✅ Changing the SECRET field does not change the Current Token field even when the URI and QR code change
>     * ✅ A random SECRET instead of a static one if there isn't anything currently in local storage

<hr />

>     * ✅ Typing into the SECRET field only updates the URI field every other character, or somewhat randomly
I changed the secret field to take ASCII which is then converted to a Base32 secret instead of only allowing Base32 input which I think was a little confusing/weird.

<hr />

>     * ❓ Fixed width QR code, it's a bit large around 1190px
Changed breakpoint to stay on 3 column layout for longer, let me know if you still would like to see a max width.  

>     * A countdown timer for the Token field
I messed with this for a bit but couldn't figure out a good strategy for getting it implemented. I'm not in the React world much these days.

**Review by dlford — APPROVED** [review]
Fantastic, thanks @mvarrieur!

**Pull request merged**
